### ISSUE TITLE
grav.Rmd

### ISSUE THREAD

**Issue by kbilsback** [ngood13/stoves_nih_2016_git#183]
wrong blanks used to correct filters in grav.Rmd file

**Comment by KFedak** [comment]
hm - hadn't we fixed this a while ago? I remember the extended conversations in May... What exactly is the problem now? Is it in the main Aim 1, and therefore also in startups and moisture content?

**Comment by nickgood** [comment]
Umm, I can check the other studies once we have the problem identified…



On Sep 18, 2017, at 2:28 PM, Kristen Fedak <notifications@github.com<mailto:notifications@github.com>> wrote:


hm - hadn't we fixed this a while ago? I remember the extended conversations in May... What exactly is the problem now? Is it in the main Aim 1, and therefore also in startups and moisture content?

**Comment by kbilsback** [comment]
Kristen - aren't you supposed to be enjoying Sydney?!
Right now we are correcting using the filter room blanks and should be correcting using the lab blanks. I will fix in aim 1, but it shouldn't impact the PM EFs noticeably. More concerning thing to me right now is that I'm getting ec + oc + ions > grav, but working of figuring out where the issue is now...

**Comment by nickgood** [comment]
So, how does one distinguish between a lab and filter room blank? It looks, like they are all labelled lab blanks in the data file?

FYI - Lizette isn’t considering the blank value in her analysis at present, and the start-up is using a correct method (provided what is called lab blank in the log really is a lab blank :-))


---

Nicholas Good, BSc. PhD.
Environmental and Radiological Health Sciences
Colorado State University
Fort Collins
Colorado
80523-1681

Tel: +1.970.491.7607
Alt: +1.970.310.3750
Email: n.good@colostate.edu<mailto:n.good@colostate.edu>

On Sep 18, 2017, at 15:01, Kelsey <notifications@github.com<mailto:notifications@github.com>> wrote:


Kristen - aren't you supposed to be enjoying Sydney?!
Right now we are correcting using the filter room blanks and should be correcting using the lab blanks. I will fix in aim 1, but it shouldn't impact the PM EFs noticeably. More concerning thing to me right now is that I'm getting ec + oc + ions > grav, but working of figuring out where the issue is now...

**Comment by kbilsback** [comment]
Lab blank in filter weighing file should be used for correcting for day-to-day variability in scale room and BXX filters used to establish lod/loq for study. Fixed in "master_kb" for overall aim 1 study.
