### ISSUE TITLE
Whereabouts of written notes to compare to electronic logs

### ISSUE THREAD

**Issue by tcolehunter** [ngood13/stoves_nih_2016_git#85]
Does someone know where the written notes associated with the electronic logs (found here <E:\Cookstoves\Sub Projects\NIH Cookstoves\Aim 1\data\instruments\logs>) are?

I think I saw the big folder/s with them near the desk of @KFedak the other day...

This is for the purpose of estimating the transcription error, where @ngood13 suggested to "pick two random batch and wood tests and compare the written notes to the logs."

**Comment by KFedak** [comment]
They were on my desk for the last week or so, but, I brought them home last night so that I can use them this weekend. I need them to look up the originals for confirming outliers. We have scanned copies of all of these paper files on the server, but we  can't digitally search the scanned copy for a specific test ID and they aren't in a completely logical order. If you are just at random picking a test ID to look at the paper logs, you can pick the ID from the scanned versions, and then search for it in the log. Will that work for you? If not, I'll bring them back next week...

D:\Cookstoves\Sub Projects\NIH Cookstoves\Aim 1\data\paper_backups

**Comment by tcolehunter** [comment]
Thanks @KFedak . I think I can work with these. It looks like Tester 1 scans '1' and '2' are missing - do you know why that is (or where they are)?

**Comment by KFedak** [comment]
tester 1 scan '2' is there just with a slightly different naming convention - tester1samplingscan2. I don't know where "1" is. It's possible that it is also there but just has a different name. If you look through all the files and then still think a batch is missing we can re-scan the missing ones. Lizette numbered the pages in the top right corner. But also, do you need all the files to get the assignment done?
